### ISSUE TITLE
Not an issue. Error on require('nnode')

### ISSUE THREAD

**Issue by securisec** [ikatun/nnode#2]
Just a quick question. I am requiring `nnode` in my script, but it still throws the normal SyntaxError node errors. If i run the script with `nnode 1.js`, it works fine, but if i try to run with either `node` or `nodemon`, same error. `nnode` is installed globally. 

My test script is
```javascript
require('nnode')
import { readFileSync } from "fs";
var a = readFileSync('/tmp/1.js', 'utf8')
console.log(a);
```

Error snipped:
```
import { readFileSync } from "fs";
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:84:7)
...
```

**Comment by ikatun** [comment]
The file 1.js is still parsed by node directly even if you require nnode from it. 
You must put your code in another file and then require that file from 1.js.

**Comment by ikatun** [comment]
I'll put this example in the README later today to avoid confusion :)

**Comment by securisec** [comment]
Ah thanks! Got it.

**Comment by ikatun** [comment]
Also, note that you don't have to require('nnode') if you're running the script with the nnode CLI.
